apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: qwen3-14b-awq
  namespace: NAMESPACE_PLACEHOLDER
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/runtime-version: v0.9.1.0
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime-template
    openshift.io/display-name: vLLM NVIDIA GPU ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --port=8080
    - --model=/mnt/models
    - --served-model-name={{.Name}}
    # OpenTelemetry tracing - sends traces to OTEL Collector
    - --otlp-traces-endpoint=http://otel-collector.NAMESPACE_PLACEHOLDER.svc.cluster.local:4317
    command:
    - python3
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: HF_HOME
      value: /tmp/hf_home
    - name: HOME
      value: /tmp
    - name: VLLM_USAGE_SOURCE
      value: production-docker-image
    # OpenTelemetry configuration
    - name: OTEL_SERVICE_NAME
      value: "vllm-qwen3"
    - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
      value: "true"
    image: vllm/vllm-openai:latest
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM

