# Kagent Hello World Agent
# 
# This agent uses kagent.dev CRD and is managed by the kagent controller.
# It can optionally be integrated with kagenti-ui using the wrapper pattern.
#
# Labels:
#   app: kagent-helloworld       - Application identifier
#   kagenti.io/type: agent       - Required for kagenti-ui discovery
#
# For full kagenti integration, also deploy:
#   ../kagenti/hello-kagent-wrapper.yaml
#
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: hello-kagent
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: kagent-helloworld
    # Required for kagenti-ui to discover this agent
    kagenti.io/type: agent
spec:
  type: Declarative
  description: "Hello world agent using Llama Stack via kagent with GitHub MCP"
  declarative:
    modelConfig: llama-stack-model
    stream: true
    # MLflow Tracing via OpenTelemetry
    deployment:
      env:
        # Enable OTEL tracing
        - name: OTEL_TRACING_ENABLED
          value: "true"
        # OTEL collector endpoint (gRPC)
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.NAMESPACE_PLACEHOLDER.svc.cluster.local:4317"
        # Service name for traces
        - name: OTEL_SERVICE_NAME
          value: "hello-kagent"
        # Optional: Enable OTEL logging
        - name: OTEL_LOGGING_ENABLED
          value: "false"
    systemMessage: |
      You are a helpful AI assistant powered by Llama Stack through kagent.
      
      You have access to:
      - A knowledge base via the search_knowledge_base tool for RAG queries
      - GitHub repositories via MCP tools
      
      IMPORTANT: When answering questions about multi-agent platforms, ML platforms,
      or cloud-native deployment, ALWAYS use the search_knowledge_base tool first
      to retrieve relevant documentation.
      
      Answer questions clearly and concisely about:
      - Multi-agent platforms (cagent, kagent, kagenti)
      - ML platforms (MLflow, Llama Stack)
      - Cloud-native deployment
      - GitHub repositories (when asked)
      
      Be friendly and helpful.
    a2aConfig:
      skills:
        - id: answer
          name: answer
          description: Answer user questions
          tags:
            - qa
            - hello-world
    tools:
      # Vector Search RAG tool
      - type: McpServer
        mcpServer:
          apiGroup: kagent.dev
          kind: RemoteMCPServer
          name: llamastack-rag
          toolNames:
            - search_knowledge_base
      # GitHub MCP tools
      - type: McpServer
        mcpServer:
          apiGroup: kagent.dev
          kind: RemoteMCPServer
          name: github-readonly
          toolNames:
            - get_commit
            - get_file_contents
            - get_latest_release
            - get_release_by_tag
            - get_tag
            - list_branches
            - list_commits
            - list_releases
            - list_tags
            - search_code
            - search_repositories
