apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: hello-kagent
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: kagent-helloworld
spec:
  type: Declarative
  description: "Hello world agent using Llama Stack via kagent with GitHub MCP"
  declarative:
    modelConfig: llama-stack-model
    stream: true
    systemMessage: |
      You are a helpful AI assistant powered by Llama Stack through kagent.
      
      You have access to GitHub repositories via MCP tools.
      
      Answer questions clearly and concisely about:
      - Multi-agent platforms (cagent, kagent, kagenti)
      - ML platforms (MLflow, Llama Stack)
      - Cloud-native deployment
      - GitHub repositories (when asked)
      
      Be friendly and helpful.
    a2aConfig:
      skills:
        - id: answer
          name: answer
          description: Answer user questions
          tags:
            - qa
            - hello-world
    tools:
      - type: McpServer
        mcpServer:
          apiGroup: kagent.dev
          kind: RemoteMCPServer
          name: github-readonly
          toolNames:
            - get_commit
            - get_file_contents
            - get_latest_release
            - get_release_by_tag
            - get_tag
            - list_branches
            - list_commits
            - list_releases
            - list_tags
            - search_code
            - search_repositories
