# MLflow Tracking Server Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      # Init container to create MLflow bucket in MinIO
      initContainers:
        - name: create-bucket
          image: quay.io/minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              # Wait for MinIO to be ready
              until mc alias set myminio http://mlflow-minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
                echo "Waiting for MinIO..."
                sleep 2
              done
              
              # Create mlflow bucket if it doesn't exist
              mc mb myminio/mlflow --ignore-existing
              echo "MLflow bucket ready"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-secret
                  key: MINIO_ROOT_PASSWORD
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          command:
            - /bin/sh
            - -c
          args:
            - |
              # Install required dependencies
              mkdir -p /tmp/packages && \
              pip install --target /tmp/packages --no-cache-dir psycopg2-binary boto3 && \
              export PYTHONPATH=/tmp/packages:$PYTHONPATH && \
              
              # Start MLflow server
              mlflow server \
                --host 0.0.0.0 \
                --port 5000 \
                --allowed-hosts '*' \
                --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-postgres:5432/mlflow \
                --default-artifact-root s3://mlflow/
          env:
            # PostgreSQL configuration (from secret)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgres-secret
                  key: POSTGRES_PASSWORD
            # S3/MinIO configuration
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://mlflow-minio:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-secret
                  key: MINIO_ROOT_USER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-secret
                  key: MINIO_ROOT_PASSWORD
            # Flask configuration for host access
            - name: FLASK_ALLOWED_HOSTS
              value: "*"
            - name: WERKZEUG_SKIP_HOST_CHECK
              value: "1"
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP

