# PostgreSQL Deployment and Service
# Metadata storage backend for MLflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgres
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: mlflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-postgres
  template:
    metadata:
      labels:
        app: mlflow-postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/sclorg/postgresql-16-c10s:latest
          envFrom:
            - secretRef:
                name: mlflow-postgres-secret
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U mlflow -d mlflow
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U mlflow -d mlflow
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgres
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: mlflow-postgres
spec:
  selector:
    app: mlflow-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP

