# MLflow Secrets
# Contains credentials for MinIO and PostgreSQL
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: mlflow
type: Opaque
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: miniopass123
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgres-secret
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: mlflow
type: Opaque
stringData:
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: mlflowpass
  POSTGRES_DB: mlflow

