apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-minio-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: miniopass123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-minio
  template:
    metadata:
      labels:
        app: mlflow-minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args: ["server", "/data"]
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: mlflow-minio-secret
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-minio
spec:
  selector:
    app: mlflow-minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
