apiVersion: v1
kind: Secret
metadata:
  name: github-mcp-token
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: mcp
    component: github
type: Opaque
stringData:
  token: GITHUB_TOKEN_PLACEHOLDER

